### PR TITLE
Remove generated file from tree and on clean

### PR DESCRIPTION
**Pull request by pkerling**
The Wayland protocol file is generated anyway, it should be removed from the tree.

### CODE REVIEW

**Comment by xhaihao** [comment]
Could you add a Signed-off-by tag in the commit log ?

**Comment by pkerling** [comment]
forgot about it again, sorry :( maybe you could add a commit hook that checks this?

**Comment by xhaihao** [comment]
Yes, it would be better to add a check for this, I will try to add a hook.

**Comment by xhaihao** [comment]
@uartie could you help to check what is blocking the build process?

**Pull request merged**
