### PR TITLE
VDENC: Avoid using the first index reference frame for the invalid re…

### LINKED ISSUE #70: VDENC:  VDENC_PIPE_BUF programs the valid gpu address for the invalid reference frame
Maybe the ref_list_idx[0][X] is also initialized to zero even for the invalid reference frame. In such case the VDENC_PIPE_BUF will program the valid GPU address for the invalid reference frame.
For example: FWD Ref1 is invalid

### PR DESCRIPTION
**Pull request by yakuizhao**
…ference

Maybe the ref_list_idx[0][X] is also initialized to zero even for the invalid
reference frame, which is also regarded as valid. In such case the
VDENC_PIPE_BUF will program the valid GPU address for the invalid reference.
   >For example: FWD Ref1 is invalid

Fix #70
https://github.com/01org/intel-vaapi-driver/issues/70

Signed-off-by: Zhao Yakui <yakui.zhao@intel.com>

### CODE REVIEW

**Comment by yakuizhao** [comment]
Any comment?

**Comment by yakuizhao** [comment]
any comment about this patch?

**Comment by xhaihao** [comment]
Please rebase your branch, thanks

**Comment by yakuizhao** [comment]
OK. The code is rebased. Please review it.

**Pull request merged**
