### PR TITLE
Wayland thread-safety

### PR DESCRIPTION
**Pull request by pkerling**
Fixes 01org/libva#11

It compiles, but I'm unsure how to test this. Do you know a simple program that uses the VAAPI wayland output which I could use for a test run?

### CODE REVIEW

**Comment by pkerling** [comment]
Also, why do you dynamically load everything from libwayland-client? Why don't you just link against it? It's a very light-weight library.

**Comment by xhaihao** [comment]
@pkerling  putsurface_wayland is a simple program for wayland, you can find it in libva-utils.

**Comment by xhaihao** [comment]
@pkerling  the intent is to drop explicit dependencies on wayland library, please check the commit beblow:

commit 41ceaf0fd179627960ae186f5fc3099e99157339
Author: Gwenole Beauchesne <gwenole.beauchesne@intel.com>
Date:   Mon Aug 6 16:11:47 2012 +0200

    wayland: drop explicit dependencies to Wayland libraries.

**Comment by pkerling** [comment]
Great thanks, I'll test with putsurface_wayland then and report back.

Yes I can see that it drops the dependencies, but it provides no explanation/rationale. What's different from libva itself which already has a dependency on libwayland_client?

**Comment by xhaihao** [comment]
The code was added a few years ago and I can't find the reason :(, but I agree with you that it should be fine to link against libwayland-client and simplify the code for wayland support.

**Comment by pkerling** [comment]
Mh, that's a shame - most of the time there are of course reasons why it was done this or that way. But no one knows if they still apply if they have been lost to history anyway. So I guess I'll revert the old commit, fix the conflicts, and push it here, too. This way you can easily restore the dlopen stuff if you have to by just reverting one commit.

**Comment by pkerling** [comment]
OK so I looked into it some more and `i965_output_dri.c` also uses dl-loading for `libva-x11.so`, so I guess the intention probably was to keep `i965_drv_video.so` free of direct references to any windowing systems. I'm unsure what to do here, but if this is changed then it should be done for both.

I checked the changes here with `putsurface_wayland` and it worked :) Would be cool if you could merge this, if the library loading is changed it should probably go into a new PR anyway.

**Pull request merged**
