### PR TITLE
enc: Add restriction to vp9 encoder frame rate to avoid hang

### PR DESCRIPTION
**Pull request by YuJiankang**
Temporarily limit the maximum frame rate for vp9 encoder to avoid gpu hang 
Signed-off-by: jkyu <jiankang.yu@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
please rebase

**Comment by uartie** [comment]
Is this PR still valid/needed? It has no activity for 3 months!

**Comment by xhaihao** [comment]
The shader for VP9 is designed for up to 60 fps, so please set the max value to 60 and print out a warning if user set a value greater than 60.

**Comment by xhaihao** [comment]
@YuJiankang If possible, could you update this PR?

**Comment by YuJiankang** [comment]
PR updated, please help review, thanks

**Pull request merged**
