### PR TITLE
AVC encoder rework on kbl  

### PR DESCRIPTION
**Pull request by QuPengfei**
This series of patch improve the AVC encoder on KBL

### CODE REVIEW

**Comment by QuPengfei** [comment]
patch still looks out of order. :(

**Comment by QuPengfei** [comment]
change the commit date and update.

**Comment by yakuizhao** [comment]
It seems that the avc encoding on SKL causes the B-frame issues.
It will be better that the issue is fixed firstly.

**Comment by QuPengfei** [comment]
@yakuizhao Did you see the B frames issue on SKL? or you mean sree mentioned about gstreamer-vaapi?
I do not think it is driver issue. our internal test did not show this issue.

**Pull request merged**
